### ISSUE TITLE
Redirection not working on IOS 14.2

### ISSUE THREAD

**Issue by ishaqashraf** [acquireio/acquireio-ios#1]
i am using acquire sdk for ios. when someone send msg from dashboard and on the app it will not redirect when user tap on it in IOS latest version (IOS 14.2). i tested it on IOS 14.1 and it's working fine. same issue on example project

**Comment by Chirag-Acquire** [comment]
We are currently rebuild our sdk version so that it will be fixed shortly.  Thank you for letting us know about this issue.
